src/memefeed/memefeed/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("reddit.urls")),
    path("", include("django_prometheus.urls")),
]

src/memefeed/reddit/urls.py
from django.urls import path

from .views import IndexView, SearchView, SearchResultsView, SubredditView, AuthorView
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

app_name = "reddit"
urlpatterns = [
    path(
        "subreddit/<str:subreddit_name>", SubredditView.as_view(), name="subreddit_view"
    ),
    path("author/<str:author_name>", AuthorView.as_view(), name="author_view"),
    path("search/results", SearchResultsView.as_view(), name="search_results"),
    path("search/", SearchView.as_view(), name="compose_search"),
    path("", cache_page(60 * 30)(IndexView.as_view()), name="index"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/memefeed/reddit/models.py
from django.db import models
from math import floor
from django_prometheus.models import ExportModelOperationsMixin


class Author(ExportModelOperationsMixin("author"), models.Model):
    """
    Author of a submission.
    """

    name = models.CharField(primary_key=True, max_length=20)
    favourite = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name


class Subreddit(ExportModelOperationsMixin("subreddit"), models.Model):
    """
    Subreddit.
    """

    name = models.CharField(primary_key=True, max_length=21)
    favourite = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name


class Submission(ExportModelOperationsMixin("submission"), models.Model):
    """
    Submission made on a subreddit by an Author.
    """

    id = models.CharField("Reddit post's ID", max_length=10, primary_key=True)
    title = models.CharField("Title of a Reddit post", max_length=300)
    score = models.IntegerField("Upvotes")
    url = models.URLField("Submission URL")
    permalink = models.URLField("Permalink URL", max_length=300)
    domain = models.CharField("Domain", max_length=50)
    created_utc = models.DateTimeField("Date the submission was created")
    # Submission Content / Media
    # TODO: Normalize media
    is_self = models.BooleanField(default=False)
    is_video = models.BooleanField(default=False)
    media_only = models.BooleanField(default=False)
    media = models.JSONField(default=dict, blank=True)
    media_embed = models.JSONField(default=dict)
    selftext = models.TextField(max_length=40000, default=str)
    selftext_html = models.TextField(default=str)  # TODO: Should this be binary?
    nsfw = models.BooleanField(default=False)
    thumbnail = models.URLField("Thumbnail URL")
    secure_media = models.JSONField(default=dict)
    secure_media_embed = models.JSONField(default=dict)
    # Foreign Keys
    subreddit = models.ForeignKey(Subreddit, models.CASCADE)
    author = models.ForeignKey(Author, models.CASCADE)

    class Meta:
        ordering = ["-score"]
        get_latest_by = "created_utc"


# TODO: Future sprint: Implement image server
class SubmissionFullImage(models.Model):
    """
    Full image relating to a submission.
    """

    submission = models.ForeignKey(Submission, models.CASCADE)
    image = models.ImageField(upload_to="submissions/full")
    image_ext = models.CharField("Image Extension E.G. jpg, png, gif", max_length=10)


# TODO: https://docs.djangoproject.com/en/4.1/topics/db/optimization/
# E.G. Cache queryset as a view

# TODO: Future sprint: Implement image server
class SubmissionThumbnailImage(models.Model):
    """
    Thumbnail image relating to a submission.
    """

    submission = models.ForeignKey(Submission, models.CASCADE)
    image = models.ImageField(upload_to="submissions/thumbs")
    image_ext = models.CharField("Image Extension E.G. jpg, png, gif", max_length=10)

    @property
    def span(self):
        """
        Get the most closely matching span of an image thumbnail for display in article.
        Based on image width:height ratio
        The span is a number between 1 and 3
        """
        span = floor(self.image.width / self.image.height)
        return max(min(span, 3), 1)

src/memefeed/reddit/forms.py
# https://docs.djangoproject.com/en/4.1/topics/forms/
from django import forms
from .models import Subreddit


class SearchForm(forms.Form):
    # Enumerated choices in the form of (sort_value, human_readable_value)
    sort_choices = [(0, "relevance"), (1, "score"), (2, "new"), (3, "A-Z")]
    # TODO: Implement relevance
    sort_choices_order_by = ["-score", "-score", "-created_utc", "title"]
    subreddit_choices = [
        (subreddit, subreddit) for subreddit in Subreddit.objects.all()
    ]

    # Fields in the form
    template_name = "search_form.html"
    q = forms.CharField(label="Search Term", max_length=300, required=False)
    subreddit = forms.MultipleChoiceField(
        label="r/subreddit",
        widget=forms.CheckboxSelectMultiple,
        choices=subreddit_choices,
        required=False,
    )
    author = forms.CharField(label="u/author", max_length=20, required=False)
    sort_by = forms.ChoiceField(choices=sort_choices, initial="relevance")
    nsfw_allowed = forms.BooleanField(label="Allow NSFW", required=False)

    @staticmethod
    def get_order(sort_value: int):
        try:
            return SearchForm.sort_choices_order_by[int(sort_value)]
        except Exception:
            return SearchForm.sort_choices_order_by[0]

src/memefeed/reddit/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q

from .forms import SearchForm
from .models import Submission, Subreddit, Author

from hashlib import md5
from datetime import datetime, timedelta

ITEMS_LEN = 20


class IndexView(generic.ListView):
    """
    View for index page.
    """

    template_name = "reddit/index.html"
    context_object_name = "top_submissions_list"
    paginate_by = 3

    N_DAYS_SHOWN = 1.5

    def get_queryset(self):
        """
        Returns the top submissions by score in descending order.
        Top submissions from the last N_DAYS_SHOWN of days. Hides NSFW submissions.
        The relevant 'day' for the recent top posts changes every day to make caching easier.
        Submissions are grouped into sub-lists of length = ITEMS_LEN
        """
        # Variable for how many submissions are displayed in a row in the index
        # TODO: Future sprint, implement video, galleries
        index_submission_min_date = datetime.today().astimezone() - timedelta(
            days=IndexView.N_DAYS_SHOWN
        )
        top_submissions = (
            Submission.objects.filter(created_utc__gte=index_submission_min_date)
            .filter(Q(domain__icontains="imgur.com") | Q(domain="i.redd.it"))
            .filter(nsfw=False)
            .order_by("-score")
        )

        return [
            top_submissions[i : i + ITEMS_LEN]
            for i in range(0, top_submissions.count(), ITEMS_LEN)
        ]


class SearchView(FormView):
    """
    View that composes the search/query.
    Uses SearchForm from reddit/forms.py
    """

    template_name = "reddit/search_form.html"
    form_class = SearchForm
    success_url = "search/results"


class SearchResultsView(generic.ListView):
    """
    View that displays the results of a search.
    """

    MAX_PAGE_DIGITS = 4
    template_name = "reddit/results.html"
    context_object_name = "results_list"
    model = Submission
    paginate_by = 3

    # TODO: Add form validation
    def get_context_data(self, **kwargs):
        """
        Extra arguments passed to template
        """
        context = super(SearchResultsView, self).get_context_data(**kwargs)
        context["q"] = self.request.GET.get("q")
        context["sort_by"] = self.request.GET.get("sort_by")
        # Saved context variable "results_cache_key" is results_cache_key + page number
        # Assume the number of pages will not reach MAX_PAGE_DIGITS digits
        results_cache_key = self.request.GET.get("results_cache_key")
        if results_cache_key:
            context["results_cache_key"] = results_cache_key[
                : self.MAX_PAGE_DIGITS * -1
            ] + self.request.GET.get("page").zfill(self.MAX_PAGE_DIGITS)
        else:
            # Split on argument params minus csrf_token
            try:
                url_params = (
                    self.request.get_full_path().split("&", 1)[1].encode("utf-8")
                )
                context["results_cache_key"] = md5(url_params).hexdigest()[
                    :6
                ] + "1".zfill(self.MAX_PAGE_DIGITS)
            except IndexError:
                # Invalid URL without GET params defaults to search on all records
                context["q"] = ""
                context["sort_by"] = "0"
                context["results_cache_key"] = "tempCK"
        return context

    def parse_subreddits_current_path(self):
        current_path = self.request.get_full_path()
        subreddits = [
            subreddit[10:]
            for subreddit in current_path.split("&")
            if subreddit.startswith("subreddit=")
        ]
        return subreddits

    def get_queryset(self):
        """
        Handles generation of results.
        """
        filtered_subreddits = self.parse_subreddits_current_path()
        title = self.request.GET.get("q")
        sort_by = self.request.GET.get("sort_by")
        nsfw_allowed = self.request.GET.get("nsfw_allowed")
        if sort_by:
            order = SearchForm.get_order(int(sort_by))
        else:
            order = SearchForm.get_order(0)
        query = Submission.objects.filter(
            Q(domain="i.redd.it") | Q(domain="v.redd.it") | Q(domain="i.imgur.com")
        )
        author = self.request.GET.get("author")
        if author:
            # TODO: IS this validation good enought?
            query = query.filter(author=author)
        if filtered_subreddits:
            query = query.filter(subreddit__in=filtered_subreddits)

        if title:
            # Get specific title
            query = query.filter(title__icontains=title)
        if not nsfw_allowed:
            query = query.filter(nsfw=False)
        result_submissions = query.order_by(order).all()
        return [
            result_submissions[i : i + ITEMS_LEN]
            for i in range(0, len(result_submissions), ITEMS_LEN)
        ]


class SubredditView(generic.ListView):
    """
    Best posts all time on a subreddit.
    Same as search but just filter by subreddit
    """

    template_name = "reddit/subreddit.html"
    context_object_name = "top_submissions_list"
    paginate_by = 3

    def setup(self, request, *args, **kwargs):
        """
        Setup for rendering view by getting related subreddit object
        and setting self.subreddit_not_found based on the object.
        """
        super().setup(request, *args, **kwargs)
        _subreddit_name = kwargs.get("subreddit_name", None)
        try:
            self.subreddit = Subreddit.objects.get(name=_subreddit_name)
            self.subreddit_not_found = False
        except:
            self.subreddit = None
            self.subreddit_not_found = True

    def get_context_data(self, **kwargs):
        """
        Extra arguments passed to template
        """
        context = super(SubredditView, self).get_context_data(**kwargs)
        context["subreddit"] = self.subreddit
        context["subreddit_not_found"] = self.subreddit_not_found
        return context

    def get_queryset(self):
        """
        Returns the top submissions by score in descending order.
        Submissions are grouped into sub-lists of length = ITEMS_LEN
        """
        # Variable for how many submissions are displayed in a row in the index
        # TODO: Future sprint, implement video, galleries
        #  | Q(domain="v.redd.it")
        if not self.subreddit_not_found:
            subreddit_name = self.subreddit
            top_submissions = (
                Submission.objects.filter(subreddit=subreddit_name)
                .filter(Q(domain__icontains="imgur.com") | Q(domain="i.redd.it"))
                .order_by("-score", "title")
            )
            return [
                top_submissions[i : i + ITEMS_LEN]
                for i in range(0, len(top_submissions), ITEMS_LEN)
            ]
        else:
            return []


class AuthorView(generic.ListView):
    """
    Best posts all time by an author.
    Same as search but just filter by author
    """

    template_name = "reddit/author.html"
    context_object_name = "top_submissions_list"
    paginate_by = 3

    def setup(self, request, *args, **kwargs):
        """
        Setup for rendering view by getting related author object
        and setting self.author_not_found based on the object.
        """
        super().setup(request, *args, **kwargs)
        _author_name = kwargs.get("author_name", None)
        try:
            self.author = Author.objects.get(name=_author_name)
            self.author_not_found = False
        except:
            self.author = None
            self.author_not_found = True

    def get_context_data(self, **kwargs):
        """
        Extra arguments passed to template
        """
        context = super(AuthorView, self).get_context_data(**kwargs)
        context["author"] = self.author
        context["author_not_found"] = self.author_not_found
        return context

    def get_queryset(self):
        """
        Returns the top submissions by score in descending order.
        Submissions are grouped into sub-lists of length = ITEMS_LEN
        """
        # Variable for how many submissions are displayed in a row in the index
        # TODO: Future sprint, implement video, galleries
        #  | Q(domain="v.redd.it")
        if not self.author_not_found:
            author_name = self.author
            top_submissions = (
                Submission.objects.filter(author=author_name)
                .filter(Q(domain__icontains="imgur.com") | Q(domain="i.redd.it"))
                .order_by("-score", "title")
            )
            return [
                top_submissions[i : i + ITEMS_LEN]
                for i in range(0, len(top_submissions), ITEMS_LEN)
            ]
        else:
            return []

src/memefeed/reddit/templates/reddit/author.html
{% extends "reddit/index.html" %}
{% load reddit_filter %}


{% block title %}Memefeed By Yinnerston{% endblock %}

{%block page_name %}
    {% if author_not_found %}
        <h2>Invalid author name!</h2>
    {% elif author %}
        <h2>Posts from u/{{author.name}}</h2>
    {% endif %}
{% endblock %}

{% block content %}
	{% if page_obj %}
		{% for submissions_list in page_obj %}
			<div class="items">
				{% for submission in submissions_list %}
					{% comment %}
					See src\memefeed\reddit\templatetags\reddit_filter.py for implementation
					{% endcomment %}
					<article class="item thumb span-1">
						<h2>
							<strong>{{submission.title}}</strong><a href="{{submission.permalink}}"><i class="fa fa-link" aria-hidden="true"></i></a><br>
							<a href="{% url 'reddit:author_view' submission.author %}">r/{{submission.subreddit}}</a><br>
							{{ submission.score }}⬆️ by u/{{submission.author}}
						</h2>
						{{ submission | display_media | safe }}
					</article>


				{% endfor %}
			</div>
		{% endfor %}
	{% else %}
		<p>No submissions found.</p>
	{% endif %}
{% endblock %}

src/memefeed/reddit/templates/reddit/base.html
{% load static %}
{% load reddit_filter %}
<!DOCTYPE HTML>
<!--
	Parallelism by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta charset="utf-8" />
		<link rel="shortcut icon" type="image/png" href="{% static 'reddit/images/favicon.ico' %}"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'reddit/assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'reddit/assets/css/noscript.css' %}" /></noscript>
		{% comment %} <script src="https://cdn.jsdelivr.net/npm/lazyload@2.0.0-rc.2/lazyload.js"></script> {% endcomment %}
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">
				<!-- Header -->
					<section id="header">
						<div id="headerDiv">
							{% include "reddit/header.html" %}
							{% block page_name %}{% endblock %}	
						</div>
					</section>
			<!-- Main -->
					<section id="main">

						<!-- Items -->
                        {% block content %}
                        {% endblock %}


					</section>

				<!-- Footer -->
					<section id="footer">
						<section>
							{% block footer %}{% endblock %}
						</section>
						<section>
							<ul class="icons">
								<li><a href="https://github.com/Yinnerston/memefeed" class="icon brands fa-github"><span class="label">Github</span></a></li>
								<li><a href="https://www.reddit.com/user/YinnerstonMemefeed" class="icon brands fa-reddit"><span class="label">Reddit</span></a></li>
								<li><a href="mailto:nathan.memefeed@gmail.com" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
							</ul>
							<ul class="copyright">
								<li><a href="https://github.com/Yinnerston/memefeed">Yinnerston Memefeed</a></li><li>Template from: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</section>
					</section>

			</div>

		<!-- Scripts -->
			<script src="{% static 'reddit/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'reddit/assets/js/jquery.poptrox.min.js' %}"></script>
			<script src="{% static 'reddit/assets/js/browser.min.js' %}"></script>
			<script src="{% static 'reddit/assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'reddit/assets/js/util.js' %}"></script>
			<script src="{% static 'reddit/assets/js/main.js' %}"></script>

	</body>
</html>

src/memefeed/reddit/templates/reddit/header.html
{% load static %}

<div class="headernav">
    <link rel="stylesheet" href="{% static 'reddit/assets/css/header.css' %}">
    {% url 'reddit:index' as index_url %}
    {% url 'reddit:compose_search' as compose_search_url %}
    {% comment %} {% url 'reddit:search_results' as results_url %} {% endcomment %}
    <section id="header_section1">
        <a href="{{ index_url }}"><img src="{% static 'reddit/images/memefeed-logo.svg' %}" alt="Memefeed Logo" height="64px" width="auto"></a>
    </section>
    <section id="header_section2">
        <a href="{{ compose_search_url }}"><img src="{% static 'reddit/images/compose-search-button.svg' %}" alt="Compose Search" height="64px" width="auto"></a>
    </section>
</div>

src/memefeed/reddit/templates/reddit/index.html
{% extends "reddit/base.html" %}
{% load reddit_filter %}
{% load static %}

{% block title %}Memefeed By Yinnerston{% endblock %}

{%block page_name %}
    <h2>Top Recent Posts!</h2>
{% endblock %}


{% block content %}
	{% if page_obj %}
		{% for submissions_list in page_obj %}
			<div class="items">
				{% for submission in submissions_list %}
					{% comment %}
					See src\memefeed\reddit\templatetags\reddit_filter.py for implementation
					{% endcomment %}
					<article class="item thumb span-1">
						<h2>
							<strong>{{submission.title}}</strong><a href="{{submission.permalink}}"><i class="fa fa-link" aria-hidden="true"></i></a>
							<br>
							<a href="{% url 'reddit:subreddit_view' submission.subreddit %}">r/{{submission.subreddit}}</a><br>
							{{ submission.score }}⬆️ by <a href="{% url 'reddit:author_view' submission.author %}">u/{{submission.author}}</a>
						</h2>
						{{ submission | display_media | safe }}
					</article>


				{% endfor %}
			</div>
		{% endfor %}
	{% else %}
		<p>No submissions found.</p>
	{% endif %}
{% endblock %}

{% block footer %}
	<div class="pagination">
		<span class="step-links">
			{% if page_obj.has_previous %}
				<a href="?page=1&sort_by={{ sort_by }}">&laquo; first</a>
				<a href="?page={{ page_obj.previous_page_number }}&sort_by={{ sort_by }}">previous</a>
			{% endif %}

			<span class="current">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			</span>

			{% if page_obj.has_next %}
				<a href="?page={{ page_obj.next_page_number }}&sort_by={{ sort_by }}">next</a>
				<a href="?page={{ page_obj.paginator.num_pages }}&sort_by={{ sort_by }}">last &raquo;</a>
			{% endif %}
		</span>
	</div>
	<a href="{% url 'reddit:search_results' %}">
		<h2 class="FooterIndexLink">See All</h2>
	</a>
{% endblock %}

src/memefeed/reddit/templates/reddit/results.html
{% extends "reddit/base.html" %}

{% load reddit_filter %}
{% load static %}
{% load cache %}

<link rel="stylesheet" href="{% static 'reddit/assets/css/results.css' %}" />


{% block title %}Memefeed By Yinnerston{% endblock %}


{%block page_name %}
    <h2>Results for {{ q }}</h2>
{% endblock %}

{% comment %}
Search results are cached per page
{% endcomment %}
{% block content %}
	{% cache 86400 search_result_cache results_cache_key %}
		{% if page_obj %}
			{% for submissions_list in page_obj %}
				<div class="items">
					{% for submission in submissions_list %}
						{% comment %}
						See src\memefeed\reddit\templatetags\reddit_filter.py for implementation
						{% endcomment %}
						<article class="item thumb span-1">
							<h2>
								<strong>{{submission.title}}</strong><a href="{{submission.permalink}}"><i class="fa fa-link" aria-hidden="true"></i></a><br>
								<a href="{% url 'reddit:subreddit_view' submission.subreddit %}">r/{{submission.subreddit}}</a><br>
								{{ submission.score }}⬆️ by <a href="{% url 'reddit:author_view' submission.author %}">u/{{submission.author}}</a>
							</h2>
							{{ submission | display_media | safe }}
						</article>


					{% endfor %}
				</div>
			{% endfor %}
		{% else %}
			<p>No submissions found.</p>
		{% endif %}
	{% endcache %}
{% endblock %}

{% block footer %}
	<div class="pagination">
		<span class="step-links">
			{% if page_obj.has_previous %}
				<a href="?page=1&sort_by={{ sort_by }}&results_cache_key={{ results_cache_key }}">&laquo; first</a>
				<a href="?page={{ page_obj.previous_page_number }}&sort_by={{ sort_by }}&results_cache_key={{ results_cache_key }}">previous</a>
			{% endif %}

			<span class="current">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			</span>

			{% if page_obj.has_next %}
				<a href="?page={{ page_obj.next_page_number }}&sort_by={{ sort_by }}&results_cache_key={{ results_cache_key }}">next</a>
				<a href="?page={{ page_obj.paginator.num_pages }}&sort_by={{ sort_by }}&results_cache_key={{ results_cache_key }}">last &raquo;</a>
			{% endif %}
		</span>
	</div>

	<a href="{% url 'reddit:search_results' %}">
		<h2 class="FooterIndexLink">See All</h2>
	</a>
{% endblock %}

src/memefeed/reddit/templates/reddit/search_form.html
{% include "reddit/header.html" %}
{% load static %}


<div class="searchformnav">
    <link rel="stylesheet" href="{% static 'reddit/assets/css/search_form.css' %}">
    <h1>
        Compose your search:
    </h1>
    <h3>
        Leave form fields empty to search on the entire dataset.
    </h3>
    <form action="{% url 'reddit:search_results' %}" method="get">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            <img src="{% static 'reddit/images/search_form_submit.png' %}" alt="Submit Button">
        </button>
    </form>
</div>

src/memefeed/reddit/templates/reddit/subreddit.html
{% extends "reddit/index.html" %}
{% load reddit_filter %}


{% block title %}Memefeed By Yinnerston{% endblock %}

{%block page_name %}
    {% if subreddit_not_found %}
        <h2>Invalid subreddit name!</h2>
    {% elif subreddit %}
        <h2>Posts from r/{{subreddit.name}}</h2>
    {% endif %}
{% endblock %}

{% block content %}
	{% if page_obj %}
		{% for submissions_list in page_obj %}
			<div class="items">
				{% for submission in submissions_list %}
					{% comment %}
					See src\memefeed\reddit\templatetags\reddit_filter.py for implementation
					{% endcomment %}
					<article class="item thumb span-1">
						<h2>
							<strong>{{submission.title}}</strong><a href="{{submission.permalink}}"><i class="fa fa-link" aria-hidden="true"></i></a><br>
							<a href="{% url 'reddit:subreddit_view' submission.subreddit %}">r/{{submission.subreddit}}</a><br>
							{{ submission.score }}⬆️ by <a href="{% url 'reddit:author_view' submission.author %}">u/{{submission.author}}</a>
						</h2>
						{{ submission | display_media | safe }}
					</article>


				{% endfor %}
			</div>
		{% endfor %}
	{% else %}
		<p>No submissions found.</p>
	{% endif %}
{% endblock %}